name: Run Go Checks

on:
  workflow_call:
    inputs:
      project_dir:
        description: Directory of the project to build
        required: true
        type: string

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: "${{ inputs.project_dir }}/**/go.sum"

      - name: run lints
        # We don't have OS-specific code so would be completely repetitive to run
        # lint on all of them.
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: go run ./build lint
        working-directory: ${{ inputs.project_dir }}

      - name: run tests
        run: go run ./build test
        working-directory: ${{ inputs.project_dir }}
